### ISSUE TITLE
Failed to resolve: phonepe.sdk.android.release:secure_component_sdk_production:1.5.0

### ISSUE THREAD

**Issue by mwshubham** [PhonePe/MerchantAndroidThinSDKDemo#5]
HI PhonePe Team, 

We are facing an error during the build process.

**Failed to resolve: phonepe.sdk.android.release:secure_component_sdk_production:1.5.0**

**Configuration**
For classpath 'com.android.tools.build:gradle:4.0.1'
and distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip

**Comment by sairajsawant** [comment]
PhonePe has deprecated this SDK.
The latest integration steps can be found here - https://developer.phonepe.com/v1/docs/android-intent-sdk-geting-started

**Comment by mwshubham** [comment]
Thanks, Sairaj I remember you from LinkedIn.
